version: "2"
linters:
  enable:
    - gocritic
    - govet
    - staticcheck
    - errcheck
    - lll
  settings:
    lll:
      line-length: 95
    revive:
      rules:
        - name: var-naming
          disabled: true
