linters:
  enable:
    - gocritic
    - govet
    - staticcheck
    - errcheck
    - revive 
  disable-all: false
linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
