// go:generate protoc --go_out=. protobuf/history.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: protobuf/history.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallHistory struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Version            int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LatestLogTimestamp int64                  `protobuf:"varint,4,opt,name=latest_log_timestamp,json=latestLogTimestamp,proto3" json:"latest_log_timestamp,omitempty"`
	InstallTimestamps  map[string]int64       `protobuf:"bytes,2,rep,name=install_timestamps,json=installTimestamps,proto3" json:"install_timestamps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstallHistory) Reset() {
	*x = InstallHistory{}
	mi := &file_protobuf_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallHistory) ProtoMessage() {}

func (x *InstallHistory) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallHistory.ProtoReflect.Descriptor instead.
func (*InstallHistory) Descriptor() ([]byte, []int) {
	return file_protobuf_history_proto_rawDescGZIP(), []int{0}
}

func (x *InstallHistory) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InstallHistory) GetLatestLogTimestamp() int64 {
	if x != nil {
		return x.LatestLogTimestamp
	}
	return 0
}

func (x *InstallHistory) GetInstallTimestamps() map[string]int64 {
	if x != nil {
		return x.InstallTimestamps
	}
	return nil
}

var File_protobuf_history_proto protoreflect.FileDescriptor

const file_protobuf_history_proto_rawDesc = "" +
	"\n" +
	"\x16protobuf/history.proto\x12\apkginfo\"\x87\x02\n" +
	"\x0eInstallHistory\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x120\n" +
	"\x14latest_log_timestamp\x18\x04 \x01(\x03R\x12latestLogTimestamp\x12]\n" +
	"\x12install_timestamps\x18\x02 \x03(\v2..pkginfo.InstallHistory.InstallTimestampsEntryR\x11installTimestamps\x1aD\n" +
	"\x16InstallTimestampsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01J\x04\b\x03\x10\x04B\x1cZ\x1ainternal/protobuf;protobufb\x06proto3"

var (
	file_protobuf_history_proto_rawDescOnce sync.Once
	file_protobuf_history_proto_rawDescData []byte
)

func file_protobuf_history_proto_rawDescGZIP() []byte {
	file_protobuf_history_proto_rawDescOnce.Do(func() {
		file_protobuf_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_history_proto_rawDesc), len(file_protobuf_history_proto_rawDesc)))
	})
	return file_protobuf_history_proto_rawDescData
}

var file_protobuf_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_history_proto_goTypes = []any{
	(*InstallHistory)(nil), // 0: pkginfo.InstallHistory
	nil,                    // 1: pkginfo.InstallHistory.InstallTimestampsEntry
}
var file_protobuf_history_proto_depIdxs = []int32{
	1, // 0: pkginfo.InstallHistory.install_timestamps:type_name -> pkginfo.InstallHistory.InstallTimestampsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_history_proto_init() }
func file_protobuf_history_proto_init() {
	if File_protobuf_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_history_proto_rawDesc), len(file_protobuf_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_history_proto_goTypes,
		DependencyIndexes: file_protobuf_history_proto_depIdxs,
		MessageInfos:      file_protobuf_history_proto_msgTypes,
	}.Build()
	File_protobuf_history_proto = out.File
	file_protobuf_history_proto_goTypes = nil
	file_protobuf_history_proto_depIdxs = nil
}
